### ISSUE TITLE
Can u help?

### ISSUE THREAD

**Issue by ihsanharh** [DAREALYTYGRUNN1NGARK456/uptime#1]
Sending this everytime, Eve thought I didn't add URL and
(node:5998) UnhandledPromiseRejectionWarning: TypeError: Only absolute URLs are supported

**Comment by LegendaryEmoji** [comment]
node fetch error, link is wrong

**Comment by ihsanharh** [comment]
It's still error ,I didn't add link didn't do anything but it's spamming that to console, how?
Nvm I got it
